[tool.briefcase]
project_name = "PicFix"
bundle = "com.example"
version = "0.0.1"
url = "https://example.com/picfix"
license = "BSD license"
author = 'Ariel Mitnick'
author_email = "ariel.s.mitnick@gmail.com"

[tool.briefcase.app.picfix]
formal_name = "PicFix"
description = "Remove the background from your photos!"
icon = "src/picfix/resources/picfix"
sources = ['src/picfix']
requires = []


[tool.briefcase.app.picfix.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.picfix.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.picfix.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.picfix.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.picfix.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
